curl   -X GET "https://fyw6lx.internetofthings.ibmcloud.com/api/v0002/bulk/devices?_limit=25" -u 'a-fyw6lx-58ie9wsuuo:8f_ZQwI+YBwSQ_pEeB'

# API key generated by Watson IoT Platform.**
# Example: a-abc123-kodl0vqqrk, where abc123 is the {orgId}


#This tells how to get the curl GET for Application API
#https://cloud.ibm.com/docs/services/IoT/reference?topic=iot-platform-api_overview#api_docs

#this tells how to get the user and password 
#the user is 'a-fyw6lx:sdfsdfsas'
#Apps -> Generate a new set of keys, I tried giving it the Standard Application.

#The output will be all the devices etc.

